generic_hw_control_loop:
  loop_hz: 30
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - dobot_m1_z_axis_joint
    - dobot_m1_axis_2_joint
    - dobot_m1_axis_3_joint
    - dobot_m1_gripper_joint
    - M14_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Joint Trajectory Controller -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - dobot_m1_z_axis_joint
    - dobot_m1_axis_2_joint
    - dobot_m1_axis_3_joint
    - dobot_m1_gripper_joint

gripper_controller:
  type: position_controllers/GripperActionController
  joint: M14_joint

#gripper_controller:
#  type: position_controllers/JointTrajectoryController
#  joints:
#    - M14_joint
